CREATE TABLE `buyers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`cnpj` varchar(18) NOT NULL,
	`razaoSocial` varchar(255),
	`nomeFantasia` varchar(255),
	`porte` varchar(50),
	`cnaePrincipal` varchar(20),
	`cnaePrincipalDescricao` text,
	`cnaesSecundarios` text,
	`regimeTributario` varchar(100),
	`dataAbertura` varchar(10),
	`situacaoCadastral` varchar(50),
	`logradouro` varchar(255),
	`numero` varchar(20),
	`complemento` varchar(255),
	`bairro` varchar(100),
	`municipio` varchar(100),
	`uf` varchar(2),
	`cep` varchar(10),
	`photoUrl` text,
	`cargo` varchar(100),
	`departamento` varchar(100),
	`telefone` varchar(20),
	`whatsapp` varchar(20),
	`interessesTexto` text,
	`categoriasInteresse` text,
	`ecossistema` varchar(100),
	`leadScore` int DEFAULT 0,
	`profileComplete` int NOT NULL DEFAULT 0,
	`status` enum('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `buyers_id` PRIMARY KEY(`id`),
	CONSTRAINT `buyers_userId_unique` UNIQUE(`userId`),
	CONSTRAINT `buyers_cnpj_unique` UNIQUE(`cnpj`)
);
